### ISSUE TITLE
Currency conversion

### ISSUE THREAD

**Issue by lludlow** [MyHush/insight-api-hush#4]
Currency conversion from HUSH to USD does not calculate properly

**Comment by covidhhle** [comment]
I'm interested in attempting a fix for this.

Would this API be acceptable? https://api.coinmarketcap.com/v1/ticker/hush/?convert=USD

**Comment by TheTrunk** [comment]
It is solved in my repo using this API.

**Comment by lludlow** [comment]
Please open a PR, I tried to edit the currency.js as you have it @TheTrunk and it causes insight to crash.

His will need to be fixed in the hush repo and tested against the code we run on the explorer

**Comment by TheTrunk** [comment]
Fixed, tested, PR opened.
